#sudo: required
dist: xenial
#virtualenv:
  #system_site_packages: true
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script: pytest
after_script: cd ~